В доктрину добавлен EventDispatcher и попытка исправления размера строк в сериализованных  данных
timepad/doctrine1 pull request #6
Opened 2021-11-29 15:30 UTC by Medreces

1. [new] [L] добавлены интерфейсы EventDispatcher
2. [new] [M] реализован дефолтный NullDispatcher + тесты на интерфейсы диспатчера
3. [new] [M] добавлен код для исправления ошибок размера строк в сериализованных данных
4. [ref] [M] исправлено поведение при ошибках десериализации: пытаемся починить, если не выходит то кидаем событие в диспатчер и считаем что данных нет (null)

https://timepad.myjetbrains.com/youtrack/issue/TPI-326

2021-12-02 10:50 UTC, zemlyannikova requested changes

2021-12-02 10:50 UTC, zemlyannikova commented on lib/Doctrine/Hydrator/ScalarDriver.php
> +                    if (false === strpos($e->getMessage(), 'Unserialization')) {
Лучше завести отдельный тип наследник Doctrine_Table_Exception для ошибок сериализации. Так надежнее чем ориентироваться на текст сообщения.

2021-12-02 13:35 UTC, Medreces commented on lib/Doctrine/Hydrator/ScalarDriver.php
> +                    if (false === strpos($e->getMessage(), 'Unserialization')) {
Да, так правильнее

2021-12-03 11:00 UTC, zemlyannikova approved these changes

2021-12-29 17:12 UTC, merged